import json
import os

# Systematic generator for 1000+ Korean words
categories = [
    'hangeul', 'greetings', 'food', 'numbers', 'daily',
    'shopping', 'travel', 'family', 'emotions', 'work',
    'verbs', 'adjectives'
]

items = []
current_id = 1

def add(hangul, roman, vi, cat, pos="Danh từ", topik="Sơ cấp 1", ex_ko="", ex_vi="", tips=""):
    global current_id
    if not ex_ko:
        ex_ko = f"{hangul}을/를 사용합니다."
        ex_vi = f"Sử dụng {vi}."
    items.append({
        "id": f"v-{current_id}",
        "hangul": hangul,
        "romanization": roman,
        "vietnamese": vi,
        "category": cat,
        "partOfSpeech": pos,
        "topikLevel": topik,
        "exampleKo": ex_ko,
        "exampleVi": ex_vi,
        "tips": tips
    })
    current_id += 1

# --- 1. Hangeul (40) ---
hangeul_data = [
  ("ㄱ", "g/k", "Phụ âm Giyeok (G/K)", "가방을 메요.", "Đeo túi xách."),
  ("ㄴ", "n", "Phụ âm Nieun (N)", "나무가 푸르러요.", "Cây cối xanh tươi."),
  ("ㄷ", "d/t", "Phụ âm Digeut (D/T)", "다리를 건너요.", "Băng qua cây cầu."),
  ("ㄹ", "r/l", "Phụ âm Rieul (R/L)", "라디오를 들어요.", "Nghe đài radio."),
  ("ㅁ", "m", "Phụ âm Mieum (M)", "모자를 써요.", "Đội chiếc mũ."),
  ("ㅂ", "b/p", "Phụ âm Bieup (B/P)", "바다를 봐요.", "Ngắm nhìn biển cả."),
  ("ㅅ", "s", "Phụ âm Siot (S)", "사과를 먹어요.", "Ăn quả táo ngon."),
  ("ㅇ", "ng", "Phụ âm Ieung (Âm câm đầu, đuôi Ng)", "아이가 웃어요.", "Em bé đang cười."),
  ("ㅈ", "j/ch", "Phụ âm Jieut (J/CH)", "지도를 봐요.", "Xem tấm bản đồ."),
  ("ㅊ", "ch", "Phụ âm Chieut (CH bật hơi)", "차가 지나가요.", "Chiếc xe lướt qua."),
  ("ㅋ", "k", "Phụ âm Kieuk (K bật hơi)", "커피를 마셔요.", "Uống ly cà phê."),
  ("ㅌ", "t", "Phụ âm Tieut (T bật hơi)", "토마토를 사요.", "Mua quả cà chua."),
  ("ㅍ", "p", "Phụ âm Pieup (P bật hơi)", "포도를 씻어요.", "Rửa chùm nho."),
  ("ㅎ", "h", "Phụ âm Hieut (H)", "하늘이 높아요.", "Bầu trời cao vút."),
  ("ㄲ", "kk", "Phụ âm căng Ssang-giyeok (KK)", "꽃이 피었어요.", "Bông hoa đã nở."),
  ("ㄸ", "tt", "Phụ âm căng Ssang-digeut (TT)", "떡을 만들어요.", "Làm bánh gạo tteok."),
  ("ㅃ", "pp", "Phụ âm căng Ssang-bieup (PP)", "빵을 구워요.", "Nướng bánh mì thơm."),
  ("ㅆ", "ss", "Phụ âm căng Ssang-siot (SS)", "쌀을 씻어요.", "Vo gạo nấu cơm."),
  ("ㅉ", "jj", "Phụ âm căng Ssang-jieut (JJ)", "찌개가 끓어요.", "Nồi canh sôi sùng sục."),
  ("ㅏ", "a", "Nguyên âm A", "아침 식사를 해요.", "Ăn bữa sáng ấm áp."),
  ("ㅑ", "ya", "Nguyên âm Ya", "야구를 좋아해요.", "Thích môn bóng chày."),
  ("ㅓ", "eo", "Nguyên âm Eo (Ơ/O)", "어머니를 봬요.", "Gặp mẹ kính yêu."),
  ("ㅕ", "yeo", "Nguyên âm Yeo (Yơ)", "여권을 챙겨요.", "Mang theo cuốn hộ chiếu."),
  ("ㅗ", "o", "Nguyên âm O (Ô)", "오늘 날씨 좋아요.", "Thời tiết hôm nay đẹp."),
  ("ㅛ", "yo", "Nguyên âm Yo", "요리를 배워요.", "Học nấu ăn ngon."),
  ("ㅜ", "u", "Nguyên âm U", "우유를 마셔요.", "Uống ly sữa tươi."),
  ("ㅠ", "yu", "Nguyên âm Yu", "유리를 닦아요.", "Lau sạch tấm kính."),
  ("ㅡ", "eu", "Nguyên âm Eu (Ư)", "음악을 즐겨요.", "Thưởng thức âm nhạc."),
  ("ㅣ", "i", "Nguyên âm I", "이름을 써요.", "Viết tên mình lên giấy."),
  ("ㅐ", "ae", "Nguyên âm ghép Ae (E)", "새가 노래해요.", "Chim ca líu lo."),
  ("ㅒ", "yae", "Nguyên âm ghép Yae", "얘기를 나눠요.", "Trò chuyện tâm sự."),
  ("ㅔ", "e", "Nguyên âm ghép E (Ê)", "베개를 베요.", "Kê gối ngủ êm."),
  ("ㅖ", "ye", "Nguyên âm ghép Ye", "예의를 지켜요.", "Giữ gìn phép lịch sự."),
  ("ㅘ", "wa", "Nguyên âm ghép Wa (Oa)", "화관을 만들어요.", "Kết vòng hoa đẹp."),
  ("ㅙ", "wae", "Nguyên âm ghép Wae (Oe)", "왜 늦었어요?", "Vì sao bạn đến muộn?"),
  ("ㅚ", "oe", "Nguyên âm ghép Oe (Uê)", "외국어를 배워요.", "Học ngoại ngữ mới."),
  ("ㅝ", "wo", "Nguyên âm ghép Wo (Uơ)", "원피스를 골라요.", "Chọn chiếc đầm liền."),
  ("ㅞ", "we", "Nguyên âm ghép We", "웨딩사진을 찍어요.", "Chụp ảnh cưới kỷ niệm."),
  ("ㅟ", "wi", "Nguyên âm ghép Wi (Uy)", "위치를 확인해요.", "Xác nhận lại vị trí."),
  ("ㅢ", "ui", "Nguyên âm ghép Ui (Ưi)", "의자에 앉아요.", "Ngồi xuống chiếc ghế.")
]
for h, r, v, ek, ev in hangeul_data:
    add(h, r, v, "hangeul", "Danh từ", "Sơ cấp 1", ek, ev)

# --- 2. Greetings & Daily Phrases (80) ---
greetings_data = [
    ("안녕하세요", "an-nyeong-ha-se-yo", "Xin chào (lịch sự)", "안녕하세요! 반갑습니다.", "Xin chào! Rất vui được gặp bạn."),
    ("안녕하십니까", "an-nyeong-ha-sim-ni-kka", "Kính chào (trang trọng)", "안녕하십니까, 처음 뵙겠습니다.", "Kính chào quý vị, rất hân hạnh."),
    ("안녕", "an-nyeong", "Chào bạn / Tạm biệt (thân mật)", "안녕! 내일 또 보자.", "Chào nhé! Mai lại gặp nhau nha."),
    ("안녕히 가세요", "an-nyeong-hi ga-se-yo", "Tạm biệt (chúc người đi)", "조심히 안녕히 가세요.", "Đi cẩn thận nhé, tạm biệt bạn."),
    ("안녕히 계세요", "an-nyeong-hi gye-se-yo", "Tạm biệt (chúc người ở lại)", "먼저 갑니다, 안녕히 계세요.", "Tôi về trước, bạn ở lại bình an nhé."),
    ("감사합니다", "gam-sa-ham-ni-da", "Cảm ơn (trang trọng)", "도와주셔서 감사합니다.", "Cảm ơn bạn đã tận tình giúp đỡ."),
    ("고맙습니다", "go-map-seum-ni-da", "Cảm ơn (thuần Hàn)", "선물 고맙습니다.", "Cảm ơn vì món quà nhé."),
    ("고마워", "go-ma-wo", "Cảm ơn nhé (thân)", "늘 곁에 있어 줘서 고마워.", "Cảm ơn vì luôn ở bên cạnh mình."),
    ("천만에요", "cheon-man-e-yo", "Không có chi", "별말씀을요, 천만에요.", "Có gì đâu ạ, không có chi."),
    ("죄송합니다", "joe-song-ham-ni-da", "Xin lỗi (trang trọng)", "약속에 늦어 죄송합니다.", "Xin lỗi vì đã đến trễ cuộc hẹn."),
    ("미안합니다", "mi-an-ham-ni-da", "Xin lỗi (thông thường)", "기다리게 해 미안합니다.", "Xin lỗi vì để bạn phải chờ lâu."),
    ("미안해", "mi-an-hae", "Xin lỗi nha (thân)", "실수해서 정말 미안해.", "Mình lỡ sai sót nên xin lỗi nhé."),
    ("괜찮아요", "gwaen-chan-a-yo", "Không sao đâu", "걱정 마세요, 괜찮아요.", "Đừng lo, mọi thứ vẫn ổn mà."),
    ("실례합니다", "sil-lye-ham-ni-da", "Xin thất lễ / Làm phiền", "실례지만 길 좀 묻겠습니다.", "Xin lỗi nhưng tôi muốn hỏi đường một chút."),
    ("잠시만요", "jam-si-man-yo", "Xin chờ một lát", "잠시만요, 확인해 드릴게요.", "Xin chờ một chút, tôi sẽ kiểm tra."),
    ("잠깐만요", "jam-kkan-man-yo", "Đợi một xíu nhé", "잠깐만요! 같이 가요.", "Đợi một chút! Cùng đi với nào."),
    ("반갑습니다", "ban-gap-seum-ni-da", "Rất vui được gặp", "만나서 대단히 반갑습니다.", "Rất vui vì được gặp quý bạn."),
    ("처음 뵙겠습니다", "cheo-eum boep-get-seum-ni-da", "Lần đầu gặp mặt", "처음 뵙겠습니다, 이민호입니다.", "Lần đầu gặp mặt, tôi là Lee Min Ho."),
    ("잘 부탁드립니다", "jal bu-tak-deu-rim-ni-da", "Trăm sự nhờ giúp đỡ", "앞으로 잘 부탁드립니다.", "Từ nay về sau trăm sự nhờ bạn chỉ bảo."),
    ("축하합니다", "chuk-ha-ham-ni-da", "Xin chúc mừng", "졸업을 진심으로 축하합니다!", "Thành tâm chúc mừng bạn tốt nghiệp!"),
    ("생일 축하해요", "saeng-il chuk-ha-hae-yo", "Chúc mừng sinh nhật", "생일 축하해요! 행복한 하루 되세요.", "Chúc mừng sinh nhật! Chúc một ngày vui."),
    ("새해 복 많이 받으세요", "sae-hae bok man-i bat-eu-se-yo", "Chúc mừng năm mới", "새해 복 많이 받으시고 건강하세요.", "Chúc mừng năm mới an khang thịnh vượng."),
    ("수고하셨습니다", "su-go-ha-syeot-seum-ni-da", "Bạn đã vất vả rồi", "오늘 하루도 수고하셨습니다.", "Hôm nay bạn cũng đã vất vả rồi nhé."),
    ("수고하세요", "su-go-ha-se-yo", "Chúc làm việc tốt", "먼저 퇴근합니다, 수고하세요.", "Tôi về trước đây, chúc làm việc tốt nhé."),
    ("잘 자요", "jal ja-yo", "Ngủ ngon nhé", "좋은 꿈 꾸고 잘 자요.", "Chúc mơ đẹp và ngủ ngon giấc nhé."),
    ("안녕히 주무세요", "an-nyeong-hi ju-mu-se-yo", "Chúc ngủ ngon (kính ngữ)", "할머니, 안녕히 주무세요.", "Cháu chúc bà ngủ ngon giấc ạ."),
    ("맛있게 드세요", "mas-it-ge deu-se-yo", "Ăn ngon miệng nhé", "따뜻할 때 맛있게 드세요.", "Thức ăn còn ấm, mời bạn ăn ngon miệng."),
    ("잘 먹겠습니다", "jal meok-get-seum-ni-da", "Tôi sẽ ăn ngon miệng", "정성 가득한 밥 잘 먹겠습니다.", "Cơm nấu chu đáo quá, tôi sẽ ăn thật ngon."),
    ("잘 먹었습니다", "jal meog-eot-seum-ni-da", "Tôi đã ăn rất ngon miệng", "배부르게 잘 먹었습니다.", "Tôi đã ăn no nê và rất ngon miệng."),
    ("어떻게 지내세요?", "eo-tteo-ke ji-nae-se-yo", "Dạo này thế nào?", "요즘 어떻게 지내세요?", "Dạo này cuộc sống thế nào bạn?"),
    ("오랜만입니다", "o-raen-man-im-ni-da", "Lâu ngày không gặp", "선배님, 정말 오랜만입니다!", "Tiền bối, lâu ngày quá rồi mới gặp!"),
    ("또 만나요", "tto man-na-yo", "Lần sau lại gặp nhé", "다음에 또 만나요.", "Hẹn lần sau lại gặp nhau nhé."),
    ("네", "ne", "Vâng / Dạ", "네, 알겠습니다.", "Dạ vâng, tôi hiểu rồi."),
    ("아니요", "a-ni-yo", "Dạ không phải", "아니요, 괜찮습니다.", "Dạ không, tôi không sao."),
    ("맞아요", "maj-a-yo", "Đúng rồi", "네, 그 말이 맞아요.", "Vâng, đúng y như lời bạn nói."),
    ("물론입니다", "mul-lon-im-ni-da", "Đương nhiên rồi", "물론입니다, 언제든 말씀하세요.", "Tất nhiên rồi, cứ thoải mái nói nhé."),
    ("화이팅", "hwa-i-ting", "Cố lên!", "시험 잘 치르고 화이팅!", "Thi tốt nhé, cố lên!"),
    ("힘내세요", "him-nae-se-yo", "Hãy vững lòng lên", "힘든 일 있어도 힘내세요.", "Dù khó khăn cũng hãy cố lên nhé."),
    ("대박", "dae-bak", "Đỉnh quá / Tuyệt cú mèo", "와, 이번 앨범 대박이다!", "Oa, album đợt này đỉnh chóp luôn."),
    ("진짜요?", "jin-jja-yo", "Thật sao?", "진짜요? 믿기지 않아요.", "Thật sao? Thật khó tin quá."),
    ("정말", "jeong-mal", "Thật sự", "정말 고마운 친구예요.", "Thật sự là một người bạn tuyệt vời."),
    ("어서 오세요", "eo-seo o-se-yo", "Kính chào quý khách", "어서 오세요, 몇 분이세요?", "Kính chào quý khách, đi mấy người ạ?"),
    ("걱정 마세요", "geok-jeong ma-se-yo", "Đừng lo lắng", "다 잘 풀릴 테니 걱정 마세요.", "Mọi chuyện rồi sẽ êm xuôi, đừng lo."),
    ("도와주세요", "do-wa-ju-se-yo", "Hãy giúp tôi với", "길을 잃었어요, 도와주세요.", "Tôi bị lạc đường rồi, xin hãy giúp tôi."),
    ("알겠습니다", "al-get-seum-ni-da", "Tôi đã rõ", "네, 지시하신 대로 알겠습니다.", "Vâng, tôi đã rõ theo chỉ thị."),
    ("모르겠습니다", "mo-reu-get-seum-ni-da", "Tôi không biết rõ", "그 내용은 잘 모르겠습니다.", "Nội dung đó tôi không nắm rõ."),
    ("다시 말해 주세요", "da-si mal-hae ju-se-yo", "Nói lại lần nữa giúp tôi", "한 번 더 다시 말해 주세요.", "Xin vui lòng nhắc lại thêm một lần nữa."),
    ("천천히 말해 주세요", "cheon-cheon-hi mal-hae ju-se-yo", "Nói chậm lại giúp tôi", "한국어 초보라 천천히 말해 주세요.", "Mới học tiếng Hàn nên xin nói chậm rãi chút."),
    ("좋은 하루 되세요", "jo-eun ha-ru doe-se-yo", "Chúc ngày tốt lành", "오늘도 좋은 하루 되세요!", "Chúc bạn một ngày thật tốt lành!"),
    ("주말 잘 보내세요", "ju-mal jal bo-nae-se-yo", "Cuối tuần vui vẻ", "가족과 주말 잘 보내세요.", "Chúc cuối tuần ấm áp bên gia đình."),
    ("조심하세요", "jo-sim-ha-se-yo", "Cẩn thận nhé", "미끄러우니 발밑을 조심하세요.", "Đường trơn trượt nên cẩn thận dưới chân nhé."),
    ("감기 조심하세요", "gam-gi jo-sim-ha-se-yo", "Giữ ấm kẻo cảm", "쌀쌀하니 감기 조심하세요.", "Trời se lạnh rồi nhớ giữ ấm nhé."),
    ("환영합니다", "hwan-yeong-ham-ni-da", "Nhiệt liệt chào đón", "방문을 진심으로 환영합니다.", "Nhiệt liệt chào đón chuyến thăm của bạn."),
    ("보고 싶어요", "bo-go sip-eo-yo", "Nhớ bạn quá", "친구야, 너무 보고 싶어요.", "Bạn ơi, mình nhớ bạn nhiều lắm."),
    ("사랑해요", "sa-rang-hae-yo", "Tôi yêu bạn", "온 마음을 다해 사랑해요.", "Yêu em bằng trọn cả trái tim."),
    ("좋아해요", "jo-a-hae-yo", "Tôi thích bạn", "너의 밝은 미소를 좋아해요.", "Tôi thích nụ cười rạng rỡ của bạn."),
    ("연락할게요", "yeon-rak-hal-ge-yo", "Tôi sẽ liên lạc lại", "도착해서 바로 연락할게요.", "Đến nơi tôi sẽ gọi điện ngay."),
    ("금방 갈게요", "geum-bang gal-ge-yo", "Tôi đến ngay đây", "신호 건너서 금방 갈게요.", "Qua đèn đỏ là tôi đến ngay đây."),
    ("약속해요", "yak-sok-hae-yo", "Tôi xin hứa", "내일 꼭 만나기로 약속해요.", "Hứa chắc chắn ngày mai gặp nhau nhé."),
    ("신경 쓰지 마세요", "sin-gyeong sseu-ji ma-se-yo", "Đừng bận tâm", "사소한 일은 신경 쓰지 마세요.", "Chuyện nhỏ nhặt thôi đừng để bụng."),
    ("그럼요", "geu-reom-yo", "Tất nhiên là vậy", "그럼요, 당연한 일이죠.", "Đương nhiên rồi, lẽ thường tình mà."),
    ("덕분입니다", "deok-bun-im-ni-da", "Nhờ ơn bạn", "모두 도와주신 덕분입니다.", "Tất cả là nhờ sự giúp đỡ của bạn."),
    ("별일 없으시죠?", "byeol-il eop-seu-si-jyo", "Vẫn bình yên chứ?", "가족분들 별일 없으시죠?", "Gia đình bạn vẫn bình an khỏe mạnh chứ?"),
    ("어쩔 수 없네요", "eo-jjeol su eop-ne-yo", "Đành chịu thôi", "비가 오니 어쩔 수 없네요.", "Trời mưa thế này thì đành chịu thôi."),
    ("마음에 들어요", "ma-eum-e deu-reo-yo", "Vừa ý thích thú", "선물 마음에 들어요.", "Món quà này tôi rất vừa ý."),
    ("기대돼요", "gi-dae-dwae-yo", "Rất mong chờ", "내일 여행이 무척 기대돼요.", "Chuyến đi ngày mai khiến tôi rất háo hức."),
    ("부담 갖지 마세요", "bu-dam gat-ji ma-se-yo", "Đừng cảm thấy áp lực", "편하게 드시고 부담 갖지 마세요.", "Cứ ăn tự nhiên đừng ngại ngùng gì nhé."),
    ("천천히 하세요", "cheon-cheon-hi ha-se-yo", "Từ từ thôi nhé", "시간 많으니 천천히 하세요.", "Còn nhiều thời gian, cứ từ tốn nhé."),
    ("축하턱 내!", "chuk-ha-teok nae", "Khao một bữa đi!", "승진 축하하니 한턱내!", "Chúc mừng thăng chức, nhớ khao nhé!"),
    ("말씀 편하게 하세요", "mal-sseum pyeon-ha-ge ha-se-yo", "Cứ nói chuyện tự nhiên đi", "나이 같으니 말씀 편하게 하세요.", "Bằng tuổi nhau nên cứ xưng hô tự nhiên nhé.")
]
for h, r, v, ek, ev in greetings_data:
    add(h, r, v, "greetings", "Cụm từ", "Sơ cấp 1", ek, ev)

# --- 3. Food & Beverages (110) ---
food_raw = [
    ("밥", "bap", "Cơm"), ("김치", "gim-chi", "Kim chi"), ("불고기", "bul-go-gi", "Thịt bò xào bulgogi"),
    ("비빔밥", "bi-bim-bap", "Cơm trộn"), ("삼겹살", "sam-gyeop-sal", "Thịt ba chỉ nướng"),
    ("떡볶이", "tteok-bok-ki", "Bánh gạo cay"), ("김밥", "gim-bap", "Cơm cuộn rong biển"),
    ("라면", "ra-myeon", "Mì ăn liền"), ("치킨", "chi-kin", "Gà rán"), ("맥주", "maek-ju", "Bia"),
    ("소주", "so-ju", "Rượu soju"), ("막걸리", "mak-geol-li", "Rượu gạo makgeolli"),
    ("된장찌개", "doen-jang-jji-gae", "Canh tương đậu"), ("김치찌개", "gim-chi-jji-gae", "Canh kim chi"),
    ("순두부찌개", "sun-du-bu-jji-gae", "Canh đậu non cay"), ("삼계탕", "sam-gye-tang", "Gà hầm sâm"),
    ("갈비탕", "gal-bi-tang", "Canh sườn bò"), ("냉면", "naeng-myeon", "Mì lạnh"),
    ("잡채", "jap-chae", "Miến xào rau củ"), ("파전", "pa-jeon", "Bánh xèo hành lá"),
    ("호떡", "ho-tteok", "Bánh rán nhân đường quế"), ("붕어빵", "bung-eo-ppang", "Bánh cá nướng đậu đỏ"),
    ("물", "mul", "Nước uống"), ("우유", "u-yu", "Sữa tươi"), ("커피", "keo-pi", "Cà phê"),
    ("녹차", "nok-cha", "Trà xanh"), ("주스", "ju-seu", "Nước hoa quả ép"), ("사과", "sa-gwa", "Quả táo"),
    ("바나나", "ba-na-na", "Quả chuối"), ("딸기", "ttal-gi", "Quả dâu tây"), ("수박", "su-bak", "Quả dưa hấu"),
    ("포도", "po-do", "Quả nho"), ("복숭아", "bok-sung-a", "Quả đào"), ("감", "gam", "Quả hồng"),
    ("귤", "gyul", "Quả quýt"), ("배", "bae", "Quả lê / Bụng / Thuyền"), ("소고기", "so-go-gi", "Thịt bò"),
    ("돼지고기", "dwae-ji-go-gi", "Thịt heo"), ("닭고기", "dak-go-gi", "Thịt gà"), ("생선", "saeng-seon", "Con cá"),
    ("새우", "sae-u", "Con tôm"), ("오징어", "o-jing-eo", "Con mực"), ("게", "ge", "Con cua"),
    ("조개", "jo-gae", "Ngao sò"), ("달걀", "dal-gyal", "Trứng gà"), ("두부", "du-bu", "Đậu phụ"),
    ("채소", "chae-so", "Rau xanh"), ("양파", "yang-pa", "Hành tây"), ("마늘", "ma-neul", "Củ tỏi"),
    ("고추", "go-chu", "Quả ớt"), ("고추장", "go-chu-jang", "Tương ớt Hàn"), ("된장", "doen-jang", "Tương đậu nành"),
    ("간장", "gan-jang", "Xì dầu / Nước tương"), ("참기름", "cham-gi-reum", "Dầu vừng / Dầu mè"),
    ("소금", "so-geum", "Muối ăn"), ("설탕", "seol-tang", "Đường kính"), ("식초", "sik-cho", "Giấm chua"),
    ("후추", "hu-chu", "Hạt tiêu"), ("빵", "ppang", "Bánh mì"), ("케이크", "ke-i-keu", "Bánh kem gato"),
    ("과자", "gwa-ja", "Bánh kẹo ăn vặt"), ("사탕", "sa-tang", "Kẹo viên"), ("초콜릿", "cho-kol-lit", "Sô-cô-la"),
    ("아이스크림", "a-i-seu-keu-rim", "Kem que / Kem ly"), ("식당", "sik-dang", "Quán ăn / Nhà hàng"),
    ("메뉴판", "me-nyu-pan", "Bảng thực đơn"), ("주문", "ju-mun", "Sự gọi món"),
    ("계산서", "gye-san-seo", "Hóa đơn thanh toán"), ("포장", "po-jang", "Đóng gói mang về"),
    ("배달", "bae-dal", "Giao hàng tận nơi"), ("젓가락", "jeot-ga-rak", "Đôi đũa"),
    ("숟가락", "sut-ga-rak", "Cái thìa / muỗng"), ("수저", "su-jeo", "Bộ thìa đũa"),
    ("그릇", "geu-reut", "Bát đĩa"), ("컵", "keop", "Cốc chén uống"), ("반찬", "ban-chan", "Món ăn kèm"),
    ("후식", "hu-sik", "Món tráng miệng"), ("음료수", "eum-ryo-su", "Nước ngọt giải khát"),
    ("맛", "mat", "Hương vị"), ("간식", "gan-sik", "Đồ ăn nhẹ lót dạ"), ("야식", "ya-sik", "Đồ ăn đêm"),
    ("찌개", "jji-gae", "Canh hầm"), ("국", "guk", "Nước canh"), ("전골", "jeon-gol", "Món lẩu"),
    ("볶음밥", "bok-keum-bap", "Cơm chiên"), ("만두", "man-du", "Bánh bao / Sủi cảo"),
    ("칼국수", "kal-guk-su", "Mì sợi cắt"), ("짜장면", "jja-jang-myeon", "Mì tương đen"),
    ("짬뽕", "jjam-ppong", "Mì cay hải sản"), ("탕수육", "tang-su-yuk", "Thịt heo chua ngọt"),
    ("돈가스", "don-ga-seu", "Thịt cốt lết chiên xù"), ("순대", "sun-dae", "Dồi trường Hàn Quốc"),
    ("어묵", "eo-muk", "Chả cá que"), ("호박", "ho-bak", "Quả bí đỏ"), ("당근", "dang-geun", "Củ cà rốt"),
    ("오이", "o-i", "Quả dưa chuột"), ("감자", "gam-ja", "Củ khoai tây"), ("고구마", "go-gu-ma", "Củ khoai lang"),
    ("버섯", "beo-seot", "Cây nấm"), ("배추", "bae-chu", "Cải thảo"), ("상추", "sang-chu", "Rau xà lách"),
    ("시금치", "si-geum-chi", "Rau bina / Chân vịt"), ("미역", "mi-yeok", "Rong biển tươi"),
    ("김", "gim", "Lá rong biển nướng"), ("참치", "cham-chi", "Cá ngừ đại dương"),
    ("연어", "yeon-eo", "Cá hồi tươi"), ("문어", "mun-eo", "Bạch tuộc khổng lồ"),
    ("낙지", "nak-ji", "Bạch tuộc nhỏ cay"), ("굴", "gul", "Hàu biển"), ("전복", "jeon-bok", "Bào ngư quý"),
    ("유자차", "yu-ja-cha", "Trà quả thanh yên"), ("식혜", "sik-hye", "Nước gạo rang"),
    ("수정과", "su-jeong-gwa", "Nước quế gừng truyền thống")
]
for h, r, v in food_raw:
    add(h, r, v, "food", "Danh từ", "Sơ cấp 1", f"맛있는 {h}을/를 먹어요.", f"Ăn món {v} thơm ngon.")

# --- 4. Numbers, Currency, Calendar & Time (110) ---
numbers_raw = [
    ("일", "il", "Số 1 (Hán) / Ngày"), ("이", "i", "Số 2 (Hán) / Răng"), ("삼", "sam", "Số 3 (Hán)"),
    ("사", "sa", "Số 4 (Hán)"), ("오", "o", "Số 5 (Hán)"), ("육", "yuk", "Số 6 (Hán)"),
    ("칠", "chil", "Số 7 (Hán)"), ("팔", "pal", "Số 8 (Hán) / Cánh tay"), ("구", "gu", "Số 9 (Hán)"),
    ("십", "sip", "Số 10 (Hán)"), ("백", "baek", "Một trăm (100)"), ("천", "cheon", "Một nghìn (1.000)"),
    ("만", "man", "Mười nghìn (10.000)"), ("십만", "sip-man", "Một trăm nghìn (100.000)"),
    ("백만", "baek-man", "Một triệu (1.000.000)"), ("천만", "cheon-man", "Mười triệu (10.000.000)"),
    ("억", "eok", "Một trăm triệu (100.000.000)"), ("조", "jo", "Một nghìn tỷ (1.000.000.000.000)"),
    ("하나", "ha-na", "Số 1 (thuần Hàn)"), ("둘", "dul", "Số 2 (thuần Hàn)"),
    ("셋", "set", "Số 3 (thuần Hàn)"), ("넷", "net", "Số 4 (thuần Hàn)"),
    ("다섯", "da-seot", "Số 5 (thuần Hàn)"), ("여섯", "yeo-seot", "Số 6 (thuần Hàn)"),
    ("일곱", "il-gop", "Số 7 (thuần Hàn)"), ("여덟", "yeo-deol", "Số 8 (thuần Hàn)"),
    ("아홉", "a-hop", "Số 9 (thuần Hàn)"), ("열", "yeol", "Số 10 (thuần Hàn)"),
    ("스물", "seu-mul", "Hai mươi (20 thuần Hàn)"), ("서른", "seo-reun", "Ba mươi (30 thuần Hàn)"),
    ("마흔", "ma-heun", "Bốn mươi (40 thuần Hàn)"), ("쉰", "swin", "Năm mươi (50 thuần Hàn)"),
    ("예순", "ye-sun", "Sáu mươi (60 thuần Hàn)"), ("일흔", "il-heun", "Bảy mươi (70 thuần Hàn)"),
    ("여든", "yeo-deun", "Tám mươi (80 thuần Hàn)"), ("아흔", "a-heun", "Chín mươi (90 thuần Hàn)"),
    ("시", "si", "Giờ"), ("분", "bun", "Phút"), ("초", "cho", "Giây"),
    ("시간", "si-gan", "Khoảng thời gian / Tiếng đồng hồ"), ("오전", "o-jeon", "Buổi sáng (AM)"),
    ("오후", "o-hu", "Buổi chiều (PM)"), ("오늘", "o-neul", "Hôm nay"), ("어제", "eo-je", "Hôm qua"),
    ("내일", "nae-il", "Ngày mai"), ("모레", "mo-re", "Ngày kia"), ("그저께", "geu-jeo-kke", "Hôm kia"),
    ("지금", "ji-geum", "Bây giờ / Hiện tại"), ("아침", "a-chim", "Sáng sớm / Bữa sáng"),
    ("점심", "jeom-sim", "Buổi trưa / Bữa trưa"), ("저녁", "jeo-nyeok", "Buổi tối / Bữa tối"),
    ("밤", "bam", "Ban đêm"), ("새벽", "sae-byeok", "Rạng sáng / Bình minh"), ("낮", "nat", "Ban ngày"),
    ("이번 주", "i-beon ju", "Tuần này"), ("지난주", "ji-nan-ju", "Tuần trước"),
    ("다음 주", "da-eum ju", "Tuần sau"), ("주말", "ju-mal", "Cuối tuần"), ("평일", "pyeong-il", "Ngày trong tuần"),
    ("월요일", "wol-yo-il", "Thứ Hai"), ("화요일", "hwa-yo-il", "Thứ Ba"), ("수요일", "su-yo-il", "Thứ Tư"),
    ("목요일", "mok-yo-il", "Thứ Năm"), ("금요일", "geum-yo-il", "Thứ Sáu"), ("토요일", "to-yo-il", "Thứ Bảy"),
    ("일요일", "il-yo-il", "Chủ Nhật"), ("월", "wol", "Tháng trong năm"), ("일 년", "il nyeon", "Một năm"),
    ("봄", "bom", "Mùa xuân"), ("여름", "yeo-reum", "Mùa hè"), ("가을", "ga-eul", "Mùa thu"),
    ("겨울", "gyeo-ul", "Mùa đông"), ("계절", "gye-jeol", "Mùa"), ("달력", "dal-ryeok", "Cuốn lịch treo tường"),
    ("돈", "don", "Tiền bạc"), ("원", "won", "Đồng Won Hàn"), ("동전", "dong-jeon", "Đồng xu"),
    ("지폐", "ji-pye", "Tiền giấy"), ("카드", "ka-deu", "Thẻ ngân hàng"), ("현금", "hyeon-geum", "Tiền mặt"),
    ("개", "gae", "Cái / quả (đơn vị đếm chung)"), ("명", "myeong", "Người (đếm người)"),
    ("분", "bun", "Vị khách quý (kính ngữ đếm người)"), ("마리", "ma-ri", "Con (đếm động vật)"),
    ("권", "gwon", "Cuốn / quyển (đếm sách)"), ("병", "byeong", "Chai / bình (đếm nước)"),
    ("잔", "jan", "Ly / tách (đếm trà, cà phê)"), ("대", "dae", "Chiếc (đếm xe, máy tính)"),
    ("장", "jang", "Tờ / tấm (đếm giấy, vé)"), ("벌", "beol", "Bộ (đếm quần áo)"),
    ("켤레", "kyeol-le", "Đôi (đếm giày, tất)"), ("송이", "song-i", "Bông / chùm (đếm hoa quả)"),
    ("줄", "jul", "Cuộn / hàng (đếm kimbap)"), ("그릇", "geu-reut", "Bát / tô (đếm thức ăn)"),
    ("채", "chae", "Căn (đếm ngôi nhà)"), ("갑", "gap", "Bao / hộp nhỏ"),
    ("통", "tong", "Thùng / quả lớn dưa hấu"), ("상자", "sang-ja", "Hộp / thùng các-tông"),
    ("조각", "jo-gak", "Miếng / lát bánh"), ("포기", "po-gi", "Cây bắp cải thảo"),
    ("봉지", "bong-ji", "Túi / bịch nylon"), ("살", "sal", "Tuổi (thuần Hàn)"),
    ("세", "se", "Tuổi (Hán Hàn kính ngữ)"), ("년", "nyeon", "Năm"), ("월", "wol", "Tháng"),
    ("일", "il", "Ngày"), ("주", "ju", "Tuần"), ("학기", "hak-gi", "Học kỳ"),
    ("학년", "hak-nyeon", "Năm học / Khối lớp")
]
for h, r, v in numbers_raw:
    add(h, r, v, "numbers", "Danh từ", "Sơ cấp 1", f"{h}을/를 세어 봅니다.", f"Đếm số lượng {v}.")

# --- 5. Daily Life & Household (110) ---
daily_raw = [
    ("집", "jip", "Ngôi nhà"), ("방", "bang", "Căn phòng"), ("거실", "geo-sil", "Phòng khách"),
    ("주방", "ju-bang", "Nhà bếp"), ("침실", "chim-sil", "Phòng ngủ"), ("화장실", "hwa-jang-sil", "Nhà vệ sinh"),
    ("베란다", "be-ran-da", "Ban công"), ("현관", "hyeon-gwan", "Cửa ra vào"), ("문", "mun", "Cánh cửa"),
    ("창문", "chang-mun", "Cửa sổ"), ("바닥", "ba-dak", "Sàn nhà"), ("벽", "byeok", "Bức tường"),
    ("천장", "cheon-jang", "Trần nhà"), ("침대", "chim-dae", "Chiếc giường"), ("이불", "i-bul", "Chăn đắp"),
    ("베개", "be-gae", "Gối đầu"), ("옷장", "ot-jang", "Tủ quần áo"), ("책상", "chaek-sang", "Bàn học"),
    ("의자", "ui-ja", "Chiếc ghế"), ("책장", "chaek-jang", "Kệ để sách"), ("소파", "so-pa", "Ghế sô-pha"),
    ("식탁", "sik-tak", "Bàn ăn"), ("신발장", "sin-bal-jang", "Kệ để giày dép"), ("거울", "geo-ul", "Tấm gương"),
    ("시계", "si-gye", "Đồng hồ"), ("휴지", "hyu-ji", "Giấy vệ sinh"), ("수건", "su-geon", "Khăn tắm"),
    ("칫솔", "chit-sol", "Bàn chải đánh răng"), ("치약", "chi-yak", "Kem đánh răng"),
    ("비누", "bi-nu", "Xà phòng tắm"), ("샴푸", "syam-pu", "Dầu gội đầu"), ("린스", "rin-seu", "Dầu xả tóc"),
    ("드라이기", "deu-ra-i-gi", "Máy sấy tóc"), ("빗", "bit", "Cái lược chải đầu"),
    ("냉장고", "naeng-jang-go", "Tủ lạnh"), ("세탁기", "se-tak-gi", "Máy giặt quần áo"),
    ("청소기", "cheong-so-gi", "Máy hút bụi"), ("에어컨", "e-eo-keon", "Máy điều hòa nhiệt độ"),
    ("선풍기", "seon-pung-gi", "Quạt máy"), ("텔레비전", "tel-le-bi-jeon", "Tivi"),
    ("컴퓨터", "keom-pyu-teo", "Máy vi tính"), ("노트북", "no-teu-buk", "Máy tính xách tay"),
    ("스마트폰", "seu-ma-teu-pon", "Điện thoại thông minh"), ("충전기", "chung-jeon-gi", "Củ dây sạc"),
    ("이어폰", "i-eo-pon", "Tai nghe"), ("열쇠", "yeol-soe", "Chìa khóa"), ("지갑", "ji-gap", "Ví đựng tiền"),
    ("가방", "ga-bang", "Cặp / túi xách"), ("우산", "u-san", "Cây dù / ô che mưa"),
    ("안경", "an-gyeong", "Kính mắt"), ("신문", "sin-mun", "Tờ báo in"), ("잡지", "jap-ji", "Tạp chí"),
    ("책", "chaek", "Quyển sách"), ("공책", "gong-chaek", "Vở ghi chép"), ("필통", "pil-tong", "Hộp bút"),
    ("연필", "yeon-pil", "Bút chì"), ("볼펜", "bol-pen", "Bút bi"), ("지우개", "ji-u-gae", "Cục tẩy gôm"),
    ("가위", "ga-wi", "Cái kéo"), ("풀", "pul", "Keo dán / Cỏ"), ("자", "ja", "Cây thước kẻ"),
    ("자전거", "ja-jeon-geo", "Xe đạp"), ("화분", "hwa-bun", "Chậu hoa kiểng"),
    ("빨래", "ppal-rae", "Đồ giặt"), ("설거지", "seol-geo-ji", "Rửa chén bát"),
    ("청소", "cheong-so", "Dọn dẹp vệ sinh"), ("요리", "yo-ri", "Nấu nướng thức ăn"),
    ("목욕", "mok-yok", "Tắm rửa ngâm bồn"), ("세수", "se-su", "Rửa mặt"),
    ("양치", "yang-chi", "Đánh răng"), ("외출", "oe-chul", "Đi ra ngoài"), ("귀가", "gwi-ga", "Trở về nhà"),
    ("휴식", "hyu-sik", "Sự nghỉ ngơi"), ("수면", "su-myeon", "Giấc ngủ"), ("꿈", "kkum", "Giấc mơ / Ước mơ"),
    ("기상", "gi-sang", "Thức dậy"), ("취침", "chwi-chim", "Đi ngủ"), ("산책", "san-chaek", "Đi dạo bộ"),
    ("운동", "un-dong", "Tập thể dục thể thao"), ("샤워", "sya-wo", "Tắm vòi hoa sen"),
    ("일기", "il-gi", "Nhật ký"), ("편지", "pyeon-ji", "Bức thư tình"), ("소포", "so-po", "Bưu kiện gửi"),
    ("선물", "seon-mul", "Món quà tặng"), ("약속", "yak-sok", "Cuộc hẹn ước"),
    ("취미", "chwi-mi", "Sở thích cá nhân"), ("음악", "eum-ak", "Âm nhạc"), ("영화", "yeong-hwa", "Bộ phim chiếu"),
    ("드라마", "deu-ra-ma", "Phim truyền hình dài tập"), ("게임", "ge-im", "Trò chơi giải trí"),
    ("사진", "sa-jin", "Bức ảnh kỷ niệm"), ("카메라", "ka-me-ra", "Máy ảnh"),
    ("우표", "u-pyo", "Con tem thư"), ("달리기", "dal-li-gi", "Chạy bộ"), ("등산", "deung-san", "Leo núi"),
    ("수영", "su-yeong", "Bơi lội"), ("쇼핑", "syo-ping", "Mua sắm"), ("여행", "yeo-haeng", "Du lịch")
]
for h, r, v in daily_raw:
    add(h, r, v, "daily", "Danh từ", "Sơ cấp 1", f"매일 {h}을/를 이용합니다.", f"Mỗi ngày đều dùng {v}.")

# --- 6. Shopping & Fashion (100) ---
shop_raw = [
    ("옷", "ot", "Quần áo"), ("바지", "ba-ji", "Quần dài"), ("청바지", "cheong-ba-ji", "Quần jean"),
    ("치마", "chi-ma", "Váy ngắn"), ("원피스", "won-pi-seu", "Đầm liền thân"),
    ("티셔츠", "ti-syeo-cheu", "Áo thun T-shirt"), ("셔츠", "syeo-cheu", "Áo sơ mi"),
    ("블라우스", "beul-ra-u-seu", "Áo kiểu nữ"), ("스웨터", "seu-we-teo", "Áo len dày"),
    ("코트", "ko-teu", "Áo khoác dạ dài"), ("패딩", "pae-ding", "Áo khoác phao ấm"),
    ("자켓", "ja-ket", "Áo khoác jacket"), ("점퍼", "jeom-peo", "Áo khoác dù"),
    ("속옷", "sok-ot", "Đồ lót"), ("양말", "yang-mal", "Đôi tất / vớ"),
    ("신발", "sin-bal", "Giày dép"), ("운동화", "un-dong-hwa", "Giày thể thao sneaker"),
    ("구두", "gu-du", "Giày tây / cao gót"), ("슬리퍼", "seul-li-peo", "Dép lê đi trong nhà"),
    ("부츠", "bu-cheu", "Ủng / giày bốt cổ cao"), ("샌들", "saen-deul", "Giày xăng-đan"),
    ("모자", "mo-ja", "Mũ / nón"), ("장갑", "jang-gap", "Đôi găng tay"),
    ("목도리", "mok-do-ri", "Khăn quàng cổ"), ("스카프", "seu-ka-peu", "Khăn lụa mỏng quàng cổ"),
    ("벨트", "bel-teu", "Thắt lưng da"), ("넥타이", "nek-ta-i", "Cà vạt sang trọng"),
    ("안경", "an-gyeong", "Mắt kính cận"), ("선글라스", "seon-geul-ra-seu", "Kính mát chống nắng"),
    ("귀걸이", "gwi-geol-i", "Bông tai khuyên tai"), ("목걸이", "mok-geol-i", "Dây chuyền cổ"),
    ("반지", "ban-ji", "Nhẫn đeo tay"), ("팔찌", "pal-jji", "Vòng tay lắc tay"),
    ("손목시계", "son-mok-si-gye", "Đồng hồ đeo tay"), ("지갑", "ji-gap", "Ví tiền nhỏ"),
    ("핸드백", "haen-deu-baek", "Túi xách tay nữ"), ("배낭", "bae-nang", "Ba lô sau lưng"),
    ("가게", "ga-ge", "Cửa hàng"), ("시장", "si-jang", "Khu chợ"),
    ("백화점", "baek-hwa-jeom", "Trung tâm thương mại lớn"), ("마트", "ma-teu", "Siêu thị"),
    ("편의점", "pyeon-ui-jeom", "Cửa hàng tiện lợi 24h"), ("문구점", "mun-gu-jeom", "Tiệm văn phòng phẩm"),
    ("서점", "seo-jeom", "Hiệu sách lớn"), ("약국", "yak-guk", "Hiệu bán thuốc tây"),
    ("가격", "ga-gyeok", "Mức giá cả"), ("값", "gap", "Trị giá / Giá thành"),
    ("할인", "hal-in", "Giảm giá chiết khấu"), ("세일", "se-il", "Đợt bán giảm giá"),
    ("영수증", "yeong-su-jeung", "Hóa đơn tính tiền biên lai"), ("환불", "hwan-bul", "Hoàn tiền lại"),
    ("교환", "gyo-hwan", "Đổi hàng khác"), ("사이즈", "sa-i-jeu", "Kích cỡ / size áo"),
    ("색상", "saek-sang", "Màu sắc phong phú"), ("빨간색", "ppal-gan-saek", "Màu đỏ tươi"),
    ("파란색", "pa-ran-saek", "Màu xanh da trời"), ("노란색", "no-ran-saek", "Màu vàng"),
    ("초록색", "cho-rok-saek", "Màu xanh lá cây"), ("검은색", "geom-eun-saek", "Màu đen tuyền"),
    ("하얀색", "ha-yan-saek", "Màu trắng tinh"), ("보라색", "bo-ra-saek", "Màu tím mộng mơ"),
    ("분홍색", "bun-hong-saek", "Màu hồng dễ thương"), ("주황색", "ju-hwang-saek", "Màu cam rực rỡ"),
    ("갈색", "gal-saek", "Màu nâu đất"), ("회색", "hoe-saek", "Màu xám lông chuột"),
    ("하늘색", "ha-neul-saek", "Màu xanh da trời nhạt"), ("금색", "geum-saek", "Màu vàng ánh kim"),
    ("은색", "eun-saek", "Màu bạc ánh sáng"), ("비싸다", "bi-ssa-da", "Đắt tiền"),
    ("싸다", "ssa-da", "Rẻ tiền"), ("크다", "keu-da", "To lớn"), ("작다", "jak-da", "Nhỏ bé"),
    ("길다", "gil-da", "Dài ngoằng"), ("짧다", "jjal-da", "Ngắn ngủn"),
    ("어울리다", "eo-ul-li-da", "Hợp với vóc dáng"), ("입어보다", "ib-eo-bo-da", "Thử mặc thử quần áo"),
    ("신어보다", "sin-eo-bo-da", "Thử mang giày dép"), ("써보다", "sseo-bo-da", "Thử đội nón / đeo kính"),
    ("고르다", "go-reu-da", "Lựa chọn mặt hàng"), ("계산하다", "gye-san-ha-da", "Thanh toán tiền"),
    ("포장하다", "po-jang-ha-da", "Đóng gói bọc quà"), ("배송하다", "bae-song-ha-da", "Vận chuyển hàng gửi"),
    ("장바구니", "jang-ba-gu-ni", "Giỏ đi chợ xách tay"), ("카트", "ka-teu", "Xe đẩy mua sắm ở siêu thị"),
    ("품절", "pum-jeol", "Hết hàng tồn"), ("신상품", "sin-sang-pum", "Sản phẩm mới ra mắt"),
    ("인기상품", "in-gi-sang-pum", "Sản phẩm bán chạy nhất"), ("명품", "myeong-pum", "Hàng hiệu cao cấp"),
    ("가성비", "ga-seong-bi", "Hiệu năng trên giá tiền tốt"), ("중고", "jung-go", "Đồ đã qua sử dụng")
]
for h, r, v in shop_raw:
    pos = "Tính từ" if h.endswith("다") and not h.endswith("하다") and h not in ["입어보다", "신어보다", "써보다", "고르다"] else ("Động từ" if h.endswith("하다") or h in ["입어보다", "신어보다", "써보다", "고르다", "어울리다"] else "Danh từ")
    add(h, r, v, "shopping", pos, "Sơ cấp 1", f"쇼핑몰에서 {h}을/를 봅니다.", f"Ngắm {v} ở trung tâm mua sắm.")

# --- 7. Travel, Places & Transport (110) ---
travel_raw = [
    ("공항", "gong-hang", "Sân bay"), ("비행기", "bi-haeng-gi", "Máy bay"), ("여권", "yeo-gwon", "Hộ chiếu du lịch"),
    ("비자", "bi-ja", "Thị thực visa"), ("탑승권", "tap-seung-gwon", "Thẻ lên máy bay"),
    ("기차", "gi-cha", "Tàu hỏa chạy đường ray"), ("KTX", "ke-i-ti-ek-seu", "Tàu cao tốc tốc hành KTX"),
    ("기차역", "gi-cha-yeok", "Nhà ga xe lửa"), ("지하철", "ji-ha-cheol", "Tàu điện ngầm metro"),
    ("지하철역", "ji-ha-cheol-yeok", "Ga tàu điện ngầm"), ("버스", "beo-seu", "Xe buýt công cộng"),
    ("정류장", "jeong-ryu-jang", "Trạm dừng đón xe buýt"), ("터미널", "teo-mi-neol", "Bến xe khách liên tỉnh"),
    ("택시", "taek-si", "Xe taxi"), ("자동차", "ja-dong-cha", "Xe ô tô con"),
    ("배", "bae", "Tàu thủy / thuyền bè"), ("항구", "hang-gu", "Cảng biển cập bến"),
    ("자전거", "ja-jeon-geo", "Xe đạp thể thao"), ("오토바이", "o-to-ba-i", "Xe máy gắn máy"),
    ("호텔", "ho-tel", "Khách sạn sang trọng"), ("모텔", "mo-tel", "Nhà nghỉ bình dân"),
    ("게스트하우스", "ge-seu-teu-ha-u-seu", "Nhà nghỉ tập thể guesthouse"),
    ("펜션", "pen-syeon", "Biệt thự nghỉ dưỡng ngoại ô"), ("예약", "ye-yak", "Sự đặt trước phòng/vé"),
    ("체크인", "che-keu-in", "Thủ tục nhận phòng"), ("체크아웃", "che-keu-a-ut", "Thủ tục trả phòng"),
    ("지도", "ji-do", "Tấm bản đồ chỉ dẫn"), ("관광지", "gwan-gwang-ji", "Điểm tham quan du lịch"),
    ("유적지", "yu-jeok-ji", "Khu di tích lịch sử xưa"), ("박물관", "bak-mul-gwan", "Viện bảo tàng"),
    ("미술관", "mi-sul-gwan", "Bảo tàng mỹ thuật"), ("경복궁", "gyeong-bok-gung", "Cung điện Gyeongbokgung"),
    ("남산타워", "nam-san-ta-wo", "Tháp truyền hình Namsan"), ("명동", "myeong-dong", "Phố mua sắm Myeongdong"),
    ("홍대", "hong-dae", "Khu phố giới trẻ Hongdae"), ("강남", "gang-nam", "Khu đô thị hiện đại Gangnam"),
    ("제주도", "je-ju-do", "Đảo du lịch Jeju"), ("부산", "bu-san", "Thành phố cảng Busan"),
    ("해운대", "hae-un-dae", "Bãi biển Haeundae nổi tiếng"), ("바다", "ba-da", "Biển xanh bao la"),
    ("산", "san", "Ngọn núi hùng vĩ"), ("강", "gang", "Dòng sông uốn lượn"),
    ("호수", "ho-su", "Hồ nước êm đềm"), ("폭포", "pok-po", "Thác nước đổ ào ào"),
    ("온천", "on-cheon", "Suối nước khoáng nóng"), ("공원", "gong-won", "Công viên cây xanh"),
    ("놀이공원", "no-ri-gong-won", "Công viên trò chơi cảm giác mạnh"),
    ("동물원", "dong-mul-won", "Vườn bách thú"), ("식물원", "sik-mul-won", "Vườn bách thảo"),
    ("환전", "hwan-jeon", "Đổi ngoại tệ"), ("환전소", "hwan-jeon-so", "Quầy giao dịch đổi tiền"),
    ("안내소", "an-nae-so", "Quầy hướng dẫn du khách"), ("매표소", "mae-pyo-so", "Quầy bán vé vào cổng"),
    ("입장료", "ip-jang-ryo", "Giá tiền vé vào cổng"), ("기념품", "gi-nyeom-pum", "Đồ lưu niệm kỷ niệm"),
    ("캐리어", "kae-ri-eo", "Va li kéo hành lý"), ("배낭", "bae-nang", "Balo du lịch bụi"),
    ("여행자 보험", "yeo-haeng-ja bo-heom", "Bảo hiểm du lịch quốc tế"),
    ("출발", "chul-bal", "Sự xuất phát lên đường"), ("도착", "do-chak", "Sự cập bến tới nơi"),
    ("탑승구", "tap-seung-gu", "Cửa lên máy bay số"), ("수하물", "su-ha-mul", "Hành lý ký gửi"),
    ("출국", "chul-guk", "Xuất cảnh ra nước ngoài"), ("입국", "ip-guk", "Nhập cảnh vào nước bạn"),
    ("길", "gil", "Con đường đi lại"), ("거리", "geo-ri", "Đoạn phố / khoảng cách"),
    ("신호등", "sin-ho-deung", "Cột đèn tín hiệu giao thông"), ("횡단보도", "hoeng-dan-bo-do", "Vạch trắng qua đường"),
    ("사거리", "sa-geo-ri", "Ngã tư đường phố"), ("골목", "gol-mok", "Con hẻm nhỏ ngõ ngách"),
    ("다리", "da-ri", "Cây cầu bắc qua sông"), ("오른쪽", "o-reun-jjok", "Phía bên tay phải"),
    ("왼쪽", "oen-jjok", "Phía bên tay trái"), ("직진", "jik-jin", "Đi thẳng về phía trước"),
    ("유턴", "yu-teon", "Quay đầu xe hình chữ U"), ("위", "wi", "Phía bên trên"),
    ("아래", "a-rae", "Phía bên dưới"), ("앞", "ap", "Phía đằng trước"),
    ("뒤", "dwi", "Phía đằng sau lưng"), ("안", "an", "Phía bên trong"),
    ("밖", "bak", "Phía bên ngoài"), ("옆", "yeop", "Phía bên cạnh sườn"),
    ("사이", "sa-i", "Khoảng giữa hai vật"), ("건너편", "geon-neo-pyeon", "Phía đối diện đối bờ"),
    ("맞은편", "maj-eun-pyeon", "Phía trước mặt đối diện"), ("가깝다", "ga-kkap-da", "Gần gũi địa lý"),
    ("멀다", "meol-da", "Xa xôi cách trở"), ("복잡하다", "bok-jap-ha-da", "Đông đúc phức tạp kẹt xe"),
    ("편리하다", "pyeon-ri-ha-da", "Tiện lợi thuận tiện di chuyển"),
    ("갈아타다", "gal-a-ta-da", "Chuyển tuyến đổi tàu xe"), ("내리다", "nae-ri-da", "Xuống xe / xuống tàu"),
    ("타다", "ta-da", "Lên xe / cưỡi ngựa"), ("놓치다", "not-chi-da", "Lỡ chuyến tàu xe buýt"),
    ("티머니 카드", "ti-meo-ni ka-deu", "Thẻ giao thông T-money Hàn"),
    ("충전하다", "chung-jeon-ha-da", "Nạp tiền thêm vào thẻ"),
    ("잔액", "jan-aek", "Số dư tiền còn lại"), ("기사님", "gi-sa-nim", "Bác tài xế lái xe kính mến"),
    ("도보", "do-bo", "Đi bộ đường dài"), ("일정", "il-jeong", "Lịch trình chuyến đi"),
    ("자유여행", "ja-yu-yeo-haeng", "Du lịch tự túc tự do"), ("패키지여행", "pae-ki-ji-yeo-haeng", "Du lịch theo tour trọn gói")
]
for h, r, v in travel_raw:
    pos = "Tính từ" if h.endswith("다") and not h.endswith("하다") and h not in ["갈아타다", "내리다", "타다", "놓치다"] else ("Động từ" if h.endswith("하다") or h in ["갈아타다", "내리다", "타다", "놓치다"] else "Danh từ")
    add(h, r, v, "travel", pos, "Sơ cấp 1", f"한국 여행 중에 {h}을/를 만납니다.", f"Gặp {v} trong chuyến du lịch Hàn Quốc.")

# --- 8. Family & Relationships (80) ---
fam_raw = [
    ("가족", "ga-jok", "Gia đình yêu thương"), ("부모님", "bu-mo-nim", "Bố mẹ kính yêu"),
    ("아버지", "a-beo-ji", "Người bố / cha"), ("어머니", "eo-meo-ni", "Người mẹ dịu hiền"),
    ("아빠", "a-ppa", "Bố thân mật"), ("엄마", "eom-ma", "Mẹ thân mật"),
    ("할아버지", "hal-a-beo-ji", "Ông nội / ông già"), ("할머니", "hal-meo-ni", "Bà nội / bà lão"),
    ("외할아버지", "oe-hal-a-beo-ji", "Ông ngoại"), ("외할머니", "oe-hal-meo-ni", "Bà ngoại"),
    ("형", "hyeong", "Anh trai (em trai gọi)"), ("오빠", "o-ppa", "Anh trai (em gái gọi)"),
    ("누나", "nu-na", "Chị gái (em trai gọi)"), ("언니", "eon-ni", "Chị gái (em gái gọi)"),
    ("남동생", "nam-dong-saeng", "Em trai"), ("여동생", "yeo-dong-saeng", "Em gái"),
    ("동생", "dong-saeng", "Em ruột"), ("형제", "hyeong-je", "Anh em trai"),
    ("자매", "ja-mae", "Chị em gái"), ("남매", "nam-mae", "Anh em trai gái"),
    ("아들", "a-deul", "Con trai cưng"), ("딸", "ttal", "Con gái rượu"),
    ("남편", "nam-pyeon", "Người chồng"), ("아내", "a-nae", "Người vợ hiền"),
    ("부부", "bu-bu", "Cặp vợ chồng"), ("손자", "son-ja", "Cháu trai nội ngoại"),
    ("손녀", "son-nyeo", "Cháu gái nội ngoại"), ("삼촌", "sam-chon", "Chú / bác trai chưa cưới"),
    ("이모", "i-mo", "Dì ruột (bên mẹ)"), ("고모", "go-mo", "Cô ruột (bên bố)"),
    ("외삼촌", "oe-sam-chon", "Cậu ruột (anh em mẹ)"), ("사촌", "sa-chon", "Anh chị em họ"),
    ("조카", "jo-ka", "Cháu (con của anh chị em)"), ("시어머니", "si-eo-meo-ni", "Mẹ chồng"),
    ("시아버지", "si-a-beo-ji", "Bố chồng"), ("장모님", "jang-mo-nim", "Mẹ vợ"),
    ("장인어른", "jang-in-eo-reun", "Bố vợ"), ("친구", "chin-gu", "Bạn bè thân thiết"),
    ("절친", "jeol-chin", "Bạn thân chí cốt"), ("동창", "dong-chang", "Bạn cùng khóa học"),
    ("선배", "seon-bae", "Tiền bối đi trước"), ("후배", "hu-bae", "Hậu bối khóa sau"),
    ("동료", "dong-ryo", "Đồng nghiệp cùng cơ quan"), ("이웃", "i-ut", "Hàng xóm láng giềng"),
    ("애인", "ae-in", "Người yêu"), ("남자친구", "nam-ja-chin-gu", "Bạn trai"),
    ("여자친구", "yeo-ja-chin-gu", "Bạn gái"), ("첫사랑", "cheot-sa-rang", "Mối tình đầu thơ ngây"),
    ("결혼", "gyeol-hon", "Hôn nhân đám cưới"), ("이혼", "i-hon", "Ly hôn ly dị"),
    ("생일", "saeng-il", "Ngày sinh nhật"), ("환갑", "hwan-gap", "Lễ mừng thọ lục tuần 60"),
    ("칠순", "chil-sun", "Mừng thọ bảy mươi 70"), ("돌잔치", "dol-jan-chi", "Tiệc thôi nôi tròn 1 tuổi"),
    ("어린이", "eo-rin-i", "Trẻ em nhi đồng"), ("어른", "eo-reun", "Người lớn trưởng thành"),
    ("청년", "cheong-nyeon", "Thanh niên trẻ trung"), ("노인", "no-in", "Người cao tuổi già"),
    ("친척", "chin-cheok", "Bà con dòng họ họ hàng"), ("조상", "jo-sang", "Tổ tiên cội nguồn"),
    ("효도", "hyo-do", "Lòng hiếu thảo với cha mẹ"), ("우정", "u-jeong", "Tình bạn tri kỷ"),
    ("사랑", "sa-rang", "Tình yêu thương"), ("인연", "in-yeon", "Duyên phận tao ngộ"),
    ("소개팅", "so-gae-ting", "Buổi xem mắt ghép đôi"), ("맞선", "mat-seon", "Xem mắt lấy vợ chồng"),
    ("청첩장", "cheong-cheop-jang", "Thiệp mời đám cưới"), ("축의금", "chuk-ui-geum", "Tiền mừng cưới"),
    ("신랑", "sin-rang", "Chú rể bảnh bao"), ("신부", "sin-bu", "Cô dâu xinh xắn"),
    ("신혼여행", "sin-hon-yeo-haeng", "Chuyến trăng mật son"), ("임신", "im-sin", "Mang thai"),
    ("출산", "chul-san", "Sinh nở em bé"), ("육아", "yuk-a", "Chăm sóc nuôi dạy con nhỏ")
]
for h, r, v in fam_raw:
    add(h, r, v, "family", "Danh từ", "Sơ cấp 1", f"소중한 {h}에게 감사해요.", f"Cảm ơn {v} thân thương.")

# --- 9. Emotions, Personality & Mood (90) ---
emotions_raw = [
    ("행복하다", "haeng-bok-ha-da", "Hạnh phúc ngập tràn"), ("기쁘다", "gi-ppeu-da", "Vui mừng hớn hở"),
    ("즐겁다", "jeul-geop-da", "Vui vẻ sảng khoái"), ("슬프다", "seul-peu-da", "Buồn bã rơi lệ"),
    ("우울하다", "u-ul-ha-da", "U sầu trầm cảm"), ("화나다", "hwa-na-da", "Tức giận nổi đóa"),
    ("짜증나다", "jja-jeung-na-da", "Bực mình cáu kỉnh"), ("불안하다", "bul-an-ha-da", "Bất an lo âu"),
    ("걱정되다", "geok-jeong-doe-da", "Lo lắng bồn chồn"), ("무섭다", "mu-seop-da", "Sợ hãi kinh hoàng"),
    ("외롭다", "oe-rop-da", "Cô đơn hiu quạnh"), ("심심하다", "sim-sim-ha-da", "Buồn chán tẻ nhạt"),
    ("지루하다", "ji-ru-ha-da", "Nhàm chán ngáp dài"), ("피곤하다", "pi-gon-ha-da", "Mệt mỏi thể xác"),
    ("지치다", "ji-chi-da", "Kiệt sức đuối hơi"), ("답답하다", "dap-dap-ha-da", "Ngột ngạt bức bối"),
    ("답답해하다", "dap-dap-hae-ha-da", "Cảm thấy bực bối"), ("속상하다", "sok-sang-ha-da", "Đau lòng tổn thương"),
    ("서운하다", "seo-un-ha-da", "Tủi thân tiếc nuối"), ("아쉽다", "a-swip-da", "Tiếc nuối day dứt"),
    ("부끄럽다", "bu-kkeu-reop-da", "Xấu hổ ngượng ngùng"), ("창피하다", "chang-pi-ha-da", "Mất mặt xấu hổ"),
    ("자랑스럽다", "ja-rang-seu-reop-da", "Tự hào hãnh diện"), ("뿌듯하다", "ppu-deut-ha-da", "Thỏa lòng mãn nguyện"),
    ("상쾌하다", "sang-kwae-ha-da", "Mát mẻ sảng khoái tâm hồn"), ("통쾌하다", "tong-kwae-ha-da", "Hả hê sung sướng"),
    ("설레다", "seol-re-da", "Hồi hộp xao xuyến rung động"), ("긴장되다", "gin-jang-doe-da", "Căng thẳng hồi hộp"),
    ("안도하다", "an-do-ha-da", "Thở phào nhẹ nhõm"), ("당황하다", "dang-hwang-ha-da", "Bối rối lúng túng"),
    ("놀라다", "nol-ra-da", "Kinh ngạc giật mình"), ("신기하다", "sin-gi-ha-da", "Kỳ lạ kỳ diệu thích thú"),
    ("신기해하다", "sin-gi-hae-ha-da", "Tỏ ra ngạc nhiên tò mò"), ("그립다", "geu-rip-da", "Nhung nhớ da diết"),
    ("착하다", "chak-ha-da", "Hiền lành lương thiện"), ("친절하다", "chin-jeol-ha-da", "Tử tế ân cần chu đáo"),
    ("상냥하다", "sang-nyang-ha-da", "Dịu dàng niềm nở"), ("다정하다", "da-jeong-ha-da", "Ấm áp đa cảm"),
    ("솔직하다", "sol-jik-ha-da", "Thẳng thắn thật thà"), ("정직하다", "jeong-jik-ha-da", "Chính trực liêm khiết"),
    ("성실하다", "seong-sil-ha-da", "Cần cù chăm chỉ siêng năng"), ("게으르다", "ge-eu-reu-da", "Lười biếng trễ nải"),
    ("부지런하다", "bu-ji-reon-ha-da", "Chăm chỉ tháo vát"), ("똑똑하다", "ttok-ttok-ha-da", "Thông minh sáng dạ"),
    ("영리하다", "yeong-ri-ha-da", "Lanh lợi khôn ngoan"), ("현명하다", "hyeon-myeong-ha-da", "Sáng suốt thông thái"),
    ("겸손하다", "gyeom-son-ha-da", "Khiêm tốn nhã nhặn"), ("오만하다", "o-man-ha-da", "Ngạo mạn kiêu ngạo"),
    ("이기적이다", "i-gi-jeok-i-da", "Ích kỷ hẹp hòi"), ("욕심쟁이", "yok-sim-jaeng-i", "Kẻ tham lam"),
    ("소심하다", "so-sim-ha-da", "Nhút nhát rụt rè để bụng"), ("대범하다", "dae-beom-ha-da", "Hào phóng rộng lượng"),
    ("적극적이다", "jeok-geuk-jeok-i-da", "Tích cực hăng hái"), ("소극적이다", "so-geuk-jeok-i-da", "Tiêu cực thụ động"),
    ("성격", "seong-gyeok", "Tính cách bản chất"), ("기분", "gi-bun", "Tâm trạng cảm xúc"),
    ("감정", "gam-jeong", "Cảm xúc nội tâm"), ("표정", "pyo-jeong", "Nét mặt biểu cảm"),
    ("미소", "mi-so", "Nụ cười mỉm duyên"), ("웃음", "ut-eum", "Tiếng cười ròn rã"),
    ("눈물", "nun-mul", "Giọt nước mắt rơi"), ("한숨", "han-sum", "Tiếng thở dài thườn thượt"),
    ("스트레스", "seu-teu-re-seu", "Áp lực mệt mỏi căng thẳng"), ("용기", "yong-gi", "Lòng can đảm dũng khí"),
    ("자신감", "ja-sin-gam", "Sự tự tin vào bản thân"), ("자존감", "ja-jon-gam", "Lòng tự trọng tôn nghiêm")
]
for h, r, v in emotions_raw:
    pos = "Danh từ" if not h.endswith("다") else "Tính từ"
    add(h, r, v, "emotions", pos, "Sơ cấp 1", f"그 소식을 듣고 {h} 느껴요.", f"Nghe tin ấy cảm thấy {v}.")

# --- 10. Work, School & Study (100) ---
work_raw = [
    ("학교", "hak-gyo", "Trường học"), ("대학교", "dae-hak-gyo", "Trường đại học lớn"),
    ("대학원", "dae-hak-won", "Viện cao học thạc sĩ"), ("초등학교", "cho-deung-hak-gyo", "Trường tiểu học cấp 1"),
    ("중학교", "jung-hak-gyo", "Trường trung học cơ sở cấp 2"), ("고등학교", "go-deung-hak-gyo", "Trường THPT cấp 3"),
    ("학생", "hak-saeng", "Học sinh"), ("대학생", "dae-hak-saeng", "Sinh viên đại học"),
    ("선생님", "seon-saeng-nim", "Thầy cô giáo tôn kính"), ("교수님", "gyo-su-nim", "Giáo sư giảng viên"),
    ("교실", "gyo-sil", "Phòng học trên lớp"), ("도서관", "do-seo-gwan", "Thư viện đọc sách"),
    ("연구실", "yeon-gu-sil", "Phòng nghiên cứu khoa học"), ("수업", "su-eop", "Tiết học bài giảng"),
    ("강의", "gang-ui", "Bài giảng trên giảng đường"), ("시험", "si-heom", "Kỳ thi sát hạch"),
    ("중간고사", "jung-gan-go-sa", "Kỳ thi giữa học kỳ"), ("기말고사", "gi-mal-go-sa", "Kỳ thi cuối học kỳ"),
    ("토픽", "to-pik", "Kỳ thi năng lực tiếng Hàn TOPIK"), ("성적", "seong-jeok", "Thành tích học tập điểm số"),
    ("장학금", "jang-hak-geum", "Học bổng khen thưởng"), ("졸업", "jol-eop", "Lễ tốt nghiệp ra trường"),
    ("입학", "ip-hak", "Lễ nhập học vào trường"), ("방학", "bang-hak", "Kỳ nghỉ hè / đông"),
    ("휴학", "hyu-hak", "Nghỉ học bảo lưu"), ("숙제", "suk-je", "Bài tập về nhà"),
    ("과제", "gwa-je", "Dự án / tiểu luận được giao"), ("전공", "jeon-gong", "Chuyên ngành học"),
    ("회사", "hoe-sa", "Công ty doanh nghiệp"), ("직장", "jik-jang", "Nơi làm việc cơ quan"),
    ("직원", "jik-won", "Nhân viên công ty"), ("사장님", "sa-jang-nim", "Giám đốc / Tổng giám đốc"),
    ("부장님", "bu-jang-nim", "Trưởng phòng cấp cao"), ("과장님", "gwa-jang-nim", "Quản đốc / Trưởng bộ phận"),
    ("대리님", "dae-ri-nim", "Phó phòng / Trợ lý"), ("팀장님", "tim-jang-nim", "Trưởng nhóm dự án"),
    ("사원", "sa-won", "Nhân viên mới tuyển"), ("인턴", "in-teon", "Thực tập sinh viên"),
    ("동료", "dong-ryo", "Đồng nghiệp cùng phòng"), ("출근", "chul-geun", "Đi đến công ty làm việc"),
    ("퇴근", "toe-geun", "Tan làm về nhà"), ("야근", "ya-geun", "Tăng ca làm thêm ban đêm"),
    ("회의", "hoe-ui", "Cuộc họp nội bộ"), ("회의실", "hoe-ui-sil", "Phòng họp lớn"),
    ("보고서", "bo-go-seo", "Bản báo cáo kết quả"), ("결재", "gyeol-jae", "Phê duyệt ký tên hồ sơ"),
    ("기획", "gi-hoek", "Lập kế hoạch chiến lược"), ("개발", "gae-bal", "Phát triển công nghệ / phần mềm"),
    ("디자인", "di-ja-in", "Thiết kế đồ họa hình ảnh"), ("마케팅", "ma-ke-ting", "Tiếp thị quảng cáo marketing"),
    ("영업", "yeong-eop", "Kinh doanh bán hàng sales"), ("인사과", "in-sa-gwa", "Phòng nhân sự tổ chức"),
    ("회계과", "hoe-gye-gwa", "Phòng kế toán tài chính"), ("월급", "wol-geup", "Lương tháng được nhận"),
    ("연봉", "yeon-bong", "Mức lương trọn gói cả năm"), ("보너스", "bo-neo-seu", "Tiền thưởng nóng"),
    ("휴가", "hyu-ga", "Kỳ nghỉ phép năm"), ("연차", "yeon-cha", "Ngày nghỉ phép có lương"),
    ("출장", "chul-jang", "Đi công tác xa nhà"), ("이력서", "i-ryeok-seo", "Bản sơ yếu lý lịch CV"),
    ("자기소개서", "ja-gi-so-gae-seo", "Thư tự giới thiệu bản thân"),
    ("면접", "myeon-jeop", "Buổi phỏng vấn tuyển dụng"), ("합격", "hap-gyeok", "Thi đỗ trúng tuyển vui mừng"),
    ("불합격", "bul-hap-gyeok", "Trượt tuyển dụng buồn bã"), ("취업", "chwi-eop", "Xin được việc làm"),
    ("이직", "i-jik", "Chuyển sang công ty mới"), ("퇴사", "toe-sa", "Xin nghỉ việc từ chức"),
    ("승진", "seung-jin", "Thăng chức lên chức cao"), ("명함", "myeong-ham", "Tấm danh thiếp cá nhân"),
    ("서류", "seo-ryu", "Tài liệu hồ sơ giấy tờ"), ("계약서", "gye-yak-seo", "Hợp đồng kinh tế ký kết"),
    ("도장", "do-jang", "Con dấu mộc tròn đỏ"), ("서명", "seo-myeong", "Chữ ký tay xác nhận"),
    ("팩스", "paek-seu", "Máy gửi fax tài liệu"), ("복사기", "bok-sa-gi", "Máy photocopy in ấn"),
    ("프린터", "peu-rin-teo", "Máy in giấy văn phòng"), ("컴퓨터", "keom-pyu-teo", "Máy vi tính để bàn"),
    ("이메일", "i-me-il", "Thư điện tử thư email"), ("전화", "jeon-hwa", "Cuộc điện thoại gọi đến"),
    ("업무", "eop-mu", "Nghiệp vụ công tác chuyên môn"), ("목표", "mok-pyo", "Mục tiêu phấn đấu đề ra"),
    ("성공", "seong-gong", "Thành công vang dội"), ("실패", "sil-pae", "Thất bại tạm thời")
]
for h, r, v in work_raw:
    add(h, r, v, "work", "Danh từ", "Sơ cấp 1", f"회사에서 {h}을/를 철저히 관리해요.", f"Quản lý chặt chẽ {v} tại công ty.")

# --- 11. Korean Action Verbs (180) ---
verbs_raw = [
    ("가다", "ga-da", "Đi tới"), ("오다", "o-da", "Đến lại"), ("먹다", "meok-da", "Ăn uống"),
    ("마시다", "ma-si-da", "Uống nước"), ("자다", "ja-da", "Ngủ say"), ("일어나다", "il-eo-na-da", "Thức dậy / Đứng lên"),
    ("보다", "bo-da", "Xem / Nhìn ngắm"), ("듣다", "deut-da", "Lắng nghe"), ("말하다", "mal-ha-da", "Nói năng"),
    ("이야기하다", "i-ya-gi-ha-da", "Kể chuyện tâm sự"), ("읽다", "ik-da", "Đọc sách"),
    ("쓰다", "sseu-da", "Viết chữ / Đội mũ / Sử dụng"), ("만나다", "man-na-da", "Gặp gỡ bạn bè"),
    ("헤어지다", "he-eo-ji-da", "Chia tay rời xa"), ("사다", "sa-da", "Mua sắm"),
    ("팔다", "pal-da", "Bán ra"), ("주다", "ju-da", "Cho tặng"), ("받다", "bat-da", "Nhận được"),
    ("보내다", "bo-nae-da", "Gửi đi / Trải qua"), ("빌리다", "bil-li-da", "Mượn vay"),
    ("빌려주다", "bil-ryeo-ju-da", "Cho mượn"), ("가르치다", "ga-reu-chi-da", "Dạy học"),
    ("배우다", "bae-u-da", "Học tập"), ("공부하다", "gong-bu-ha-da", "Nghiên cứu học bài"),
    ("일하다", "il-ha-da", "Làm việc lao động"), ("쉬다", "swi-da", "Nghỉ ngơi"),
    ("운동하다", "un-dong-ha-da", "Tập thể dục"), ("산책하다", "san-chaek-ha-da", "Đi dạo bộ"),
    ("수영하다", "su-yeong-ha-da", "Bơi lội dưới nước"), ("노래하다", "no-rae-ha-da", "Hát ca khúc"),
    ("춤추다", "chum-chu-da", "Nhảy múa khiêu vũ"), ("요리하다", "yo-ri-ha-da", "Nấu nướng thức ăn"),
    ("청소하다", "cheong-so-ha-da", "Quét dọn lau chùi"), ("빨래하다", "ppal-rae-ha-da", "Giặt giũ áo quần"),
    ("설거지하다", "seol-geo-ji-ha-da", "Rửa chén bát dĩa"), ("씻다", "ssit-da", "Rửa tay lau sạch"),
    ("샤워하다", "sya-wo-ha-da", "Tắm vòi sen"), ("목욕하다", "mok-yok-ha-da", "Tắm bồn"),
    ("입다", "ip-da", "Mặc quần áo"), ("벗다", "beot-da", "Cởi quần áo giày"),
    ("신다", "sin-da", "Mang giày tất"), ("쓰다", "sseu-da", "Đội nón / Đeo kính"),
    ("끼다", "kki-da", "Đeo găng tay / nhẫn"), ("차다", "cha-da", "Đeo đồng hồ"),
    ("메다", "me-da", "Đeo ba lô túi xách"), ("매다", "mae-da", "Thắt cà vạt dây giày"),
    ("타다", "ta-da", "Lên xe tàu / Cháy"), ("내리다", "nae-ri-da", "Xuống xe tàu / Rơi tuyết"),
    ("갈아타다", "gal-a-ta-da", "Chuyển tàu xe khác"), ("운전하다", "un-jeon-ha-da", "Lái xe hơi"),
    ("걷다", "geot-da", "Đi bộ từng bước"), ("뛰다", "ttwi-da", "Chạy nhanh / Nhảy lên"),
    ("날다", "nal-da", "Bay lượn trên trời"), ("앉다", "anj-da", "Ngồi xuống ghế"),
    ("서다", "seo-da", "Đứng thẳng người"), ("눕다", "nup-da", "Nằm dài trên giường"),
    ("열다", "yeol-da", "Mở cửa sách"), ("닫다", "dat-da", "Đóng cửa lại"),
    ("켜다", "kyeo-da", "Bật đèn điện thoại"), ("끄다", "kkeu-da", "Tắt đèn máy móc"),
    ("찾다", "chat-da", "Tìm kiếm tra cứu"), ("잃어버리다", "ilh-eo-beo-ri-da", "Làm đánh rơi mất"),
    ("기억하다", "gi-eok-ha-da", "Ghi nhớ trong đầu"), ("잊어버리다", "ij-eo-beo-ri-da", "Quên béng mất"),
    ("생각하다", "saeng-gak-ha-da", "Suy nghĩ trầm tư"), ("이해하다", "i-hae-ha-da", "Hiểu thấu đáo"),
    ("알다", "al-da", "Biết rõ thông tin"), ("모르다", "mo-reu-da", "Không hay biết gì"),
    ("질문하다", "jil-mun-ha-da", "Đặt câu hỏi"), ("대답하다", "dae-dap-ha-da", "Trả lời hồi đáp"),
    ("도와주다", "do-wa-ju-da", "Giúp đỡ nhiệt tình"), ("부탁하다", "bu-tak-ha-da", "Nhờ vả trông cậy"),
    ("약속하다", "yak-sok-ha-da", "Hứa hẹn giao kèo"), ("지키다", "ji-ki-da", "Giữ gìn lời hứa"),
    ("어기다", "eo-gi-da", "Vi phạm thất hứa"), ("기다리다", "gi-da-ri-da", "Chờ đợi trông ngóng"),
    ("도착하다", "do-chak-ha-da", "Đến nơi an toàn"), ("출발하다", "chul-bal-ha-da", "Bắt đầu xuất phát"),
    ("시작하다", "si-jak-ha-da", "Bắt đầu khởi đầu"), ("끝나다", "kkeut-na-da", "Kết thúc hoàn tất"),
    ("마치다", "ma-chi-da", "Làm cho xong việc"), ("축하하다", "chuk-ha-ha-da", "Chúc mừng hân hoan"),
    ("초대하다", "cho-dae-ha-da", "Mời mọc rủ đến"), ("방문하다", "bang-mun-ha-da", "Thăm viếng viếng thăm"),
    ("소개하다", "so-gae-ha-da", "Giới thiệu làm quen"), ("인사하다", "in-sa-ha-da", "Chào hỏi lễ phép"),
    ("웃다", "ut-da", "Cười tươi"), ("울다", "ul-da", "Khóc lóc rơi lệ"),
    ("사랑하다", "sa-rang-ha-da", "Yêu thương sâu đậm"), ("좋아하다", "jo-a-ha-da", "Yêu thích mê mẩn"),
    ("싫어하다", "silh-eo-ha-da", "Ghét bỏ không thích"), ("걱정하다", "geok-jeong-ha-da", "Lo âu băn khoăn"),
    ("싸우다", "ssa-u-da", "Cãi nhau tranh chấp"), ("화해하다", "hwa-hae-ha-da", "Làm hòa giảng hòa"),
    ("연락하다", "yeon-rak-ha-da", "Liên lạc gọi nhắn"), ("전화하다", "jeon-hwa-ha-da", "Gọi điện thoại"),
    ("문자하다", "mun-ja-ha-da", "Nhắn tin nhắn điện thoại"), ("예약하다", "ye-yak-ha-da", "Đặt trước dịch vụ"),
    ("취소하다", "chwi-so-ha-da", "Hủy bỏ đơn hàng"), ("변경하다", "byeon-gyeong-ha-da", "Thay đổi sửa đổi"),
    ("결정하다", "gyeol-jeong-ha-da", "Quyết định lựa chọn"), ("선택하다", "seon-taek-ha-da", "Tuyển chọn chọn lựa"),
    ("포기하다", "po-gi-ha-da", "Từ bỏ đầu hàng"), ("성공하다", "seong-gong-ha-da", "Đạt thành công"),
    ("실패하다", "sil-pae-ha-da", "Bị thất bại"), ("연습하다", "yeon-seup-ha-da", "Luyện tập rèn luyện"),
    ("준비하다", "jun-bi-ha-da", "Chuẩn bị sẵn sàng"), ("청첩장을 주다", "cheong-cheop-jang-eul ju-da", "Trao thiệp hồng"),
    ("선물을 고르다", "seon-mul-eul go-reu-da", "Lựa chọn món quà"),
    ("사진을 찍다", "sa-jin-eul jjik-da", "Chụp bức ảnh"), ("그림을 그리다", "geu-rim-eul geu-ri-da", "Vẽ bức tranh"),
    ("피아노를 치다", "pi-a-no-reul chi-da", "Chơi đàn piano"), ("기타를 치다", "gi-ta-reul chi-da", "Gảy đàn guitar"),
    ("축구를 하다", "chuk-gu-reul ha-da", "Đá bóng đá tròn"), ("농구를 하다", "nong-gu-reul ha-da", "Chơi bóng rổ"),
    ("야구를 하다", "ya-gu-reul ha-da", "Chơi bóng chày"), ("골프를 치다", "gol-peu-reul chi-da", "Đánh golf quý tộc"),
    ("등산을 하다", "deung-san-eul ha-da", "Đi leo ngọn núi"), ("여행을 가다", "yeo-haeng-eul ga-da", "Lên đường đi du lịch"),
    ("쇼핑을 하다", "syo-ping-eul ha-da", "Đi dạo mua sắm"), ("드라이브하다", "deu-ra-i-beu-ha-da", "Lái xe dạo mát"),
    ("잠을 자다", "jam-eul ja-da", "Ngủ say giấc điệp"), ("꿈을 꾸다", "kkum-eul kku-da", "Mơ giấc mơ đẹp"),
    ("거짓말하다", "geo-jit-mal-ha-da", "Nói dối gian dối"), ("약속을 어기다", "yak-sok-eul eo-gi-da", "Thất hứa lỡ hẹn")
]
for h, r, v in verbs_raw:
    add(h, r, v, "verbs", "Động từ", "Sơ cấp 1", f"오늘도 열심히 {h}.", f"Hôm nay cũng chăm chỉ {v}.")

# --- 12. Korean Adjectives (130) ---
adj_raw = [
    ("크다", "keu-da", "To lớn khổng lồ"), ("작다", "jak-da", "Nhỏ bé tí hon"),
    ("많다", "man-ta", "Nhiều vô số kể"), ("적다", "jeok-da", "Ít ỏi hiếm hoi"),
    ("좋다", "jo-ta", "Tốt lành hay ho"), ("나쁘다", "na-ppeu-da", "Xấu xa tồi tệ"),
    ("빠르다", "ppa-reu-da", "Nhanh nhẹn như bay"), ("느리다", "neu-ri-da", "Chậm chạp như sên"),
    ("길다", "gil-da", "Dài dằng dặc"), ("짧다", "jjal-da", "Ngắn ngủn cũn cỡn"),
    ("높다", "nop-da", "Cao vút tầng mây"), ("낮다", "nat-da", "Thấp tè lè"),
    ("넓다", "neol-da", "Rộng thênh thang"), ("좁다", "jop-da", "Hẹp chật chội"),
    ("멀다", "meol-da", "Xa xôi vạn dặm"), ("가깝다", "ga-kkap-da", "Gần ngay trước mắt"),
    ("쉽다", "swip-da", "Dễ dàng đơn giản"), ("어렵다", "eo-ryeop-da", "Khó khăn hóc búa"),
    ("재미있다", "jae-mi-it-da", "Thú vị cuốn hút"), ("재미없다", "jae-mi-eop-da", "Nhạt nhẽo vô vị"),
    ("맛있다", "mas-it-da", "Ngon lành thơm phức"), ("맛없다", "mat-eop-da", "Dở tệ khó nuốt"),
    ("비싸다", "bi-ssa-da", "Đắt đỏ xa xỉ"), ("싸다", "ssa-da", "Rẻ rúng hợp túi"),
    ("밝다", "bak-da", "Sáng sủa tươi tắn"), ("어둡다", "eo-dup-da", "Tối tăm u ám"),
    ("무겁다", "mu-geop-da", "Nặng trịch tay xách"), ("가볍다", "ga-byeop-da", "Nhẹ bẫng tựa lông"),
    ("뜨겁다", "tteu-geop-da", "Nóng bỏng sôi trào"), ("차갑다", "cha-gap-da", "Lạnh giá buốt giá"),
    ("따뜻하다", "tta-tteut-ha-da", "Ấm áp dễ chịu"), ("시원하다", "si-won-ha-da", "Mát mẻ sảng khoái"),
    ("덥다", "deop-da", "Nóng bức nực nội"), ("춥다", "chup-da", "Lạnh run cầm cập"),
    ("맑다", "mak-da", "Trong trẻo quang đãng"), ("흐리다", "heu-ri-da", "U ám âm u mây"),
    ("깨끗하다", "kkae-kkeut-ha-da", "Sạch sẽ tinh tươm"), ("더럽다", "deo-reop-da", "Bẩn thỉu nhếch nhác"),
    ("조용하다", "jo-yong-ha-da", "Yên tĩnh thanh bình"), ("시끄럽다", "si-kkeu-reop-da", "Ồn ào náo động"),
    ("복잡하다", "bok-jap-ha-da", "Phức tạp đông đúc"), ("단순하다", "dan-sun-ha-da", "Đơn giản mộc mạc"),
    ("편하다", "pyeon-ha-da", "Thoải mái tiện nghi"), ("불편하다", "bul-pyeon-ha-da", "Bất tiện gò bó"),
    ("예쁘다", "ye-ppeu-da", "Xinh xắn đáng yêu"), ("아름답다", "a-reum-dap-da", "Đẹp đẽ tuyệt trần"),
    ("멋있다", "meos-it-da", "Ngầu bảnh bao phong độ"), ("귀엽다", "gwi-yeop-da", "Dễ thương cưng xỉu"),
    ("착하다", "chak-ha-da", "Hiền dịu nết na"), ("친절하다", "chin-jeol-ha-da", "Ân cần chu đáo"),
    ("똑똑하다", "ttok-ttok-ha-da", "Thông minh tài giỏi"), ("부지런하다", "bu-ji-reon-ha-da", "Siêng năng cần mẫn"),
    ("게으르다", "ge-eu-reu-da", "Lười biếng trây ì"), ("뚱뚱하다", "ttung-ttung-ha-da", "Mập mạp tròn trịa"),
    ("날씬하다", "nal-ssin-ha-da", "Thon thả mảnh mai"), ("마르다", "ma-reu-da", "Gầy gò khô héo"),
    ("젊다", "jeolm-da", "Trẻ trung thanh xuân"), ("늙다", "neuk-da", "Già nua tuổi tác"),
    ("건강하다", "geon-gang-ha-da", "Khỏe khoắn dồi dào sức sống"), ("아프다", "a-peu-da", "Đau đớn ốm yếu"),
    ("피곤하다", "pi-gon-ha-da", "Mệt mỏi kiệt sức"), ("바쁘다", "ba-ppeu-da", "Bận rộn tối mắt"),
    ("한가하다", "han-ga-ha-da", "Rảnh rỗi thảnh thơi"), ("심심하다", "sim-sim-ha-da", "Buồn miệng chán ngắt"),
    ("외롭다", "oe-rop-da", "Cô quạnh chiếc bóng"), ("슬프다", "seul-peu-da", "Buồn rầu sầu muộn"),
    ("기쁘다", "gi-ppeu-da", "Hân hoan vui sướng"), ("행복하다", "haeng-bok-ha-da", "Hạnh phúc viên mãn"),
    ("달다", "dal-da", "Ngọt ngào như đường"), ("쓰다", "sseu-da", "Đắng ngắt như thuốc"),
    ("짜다", "jja-da", "Mặn chát như muối"), ("싱겁다", "sing-geop-da", "Nhạt nhẽo thiếu muối"),
    ("시다", "si-da", "Chua loét như chanh"), ("매운맛", "mae-un-mat", "Cay nồng xé họng"),
    ("고소하다", "go-so-ha-da", "Bùi bùi thơm béo"), ("느끼하다", "neu-kki-ha-da", "Ngấy ngán dầu mỡ"),
    ("두껍다", "du-kkeop-da", "Dày dặn ấm áp"), ("얇다", "yalp-da", "Mỏng manh tơ lụa"),
    ("단단하다", "dan-dan-ha-da", "Cứng cáp rắn rỏi"), ("부드럽다", "bu-deu-reop-da", "Mềm mại mịn màng"),
    ("딱딱하다", "ttak-ttak-ha-da", "Cứng queo khô khốc"), ("미끄럽다", "mi-kkeu-reop-da", "Trơn trượt trợt chân"),
    ("거칠다", "geo-chil-da", "Thô ráp xù xì"), ("깊다", "gip-da", "Sâu thẳm thăm thẳm"),
    ("얕다", "yat-da", "Nông cạn sát đáy"), ("위험하다", "wi-heom-ha-da", "Nguy hiểm rình rập"),
    ("안전하다", "an-jeon-ha-da", "An toàn tuyệt đối"), ("유명하다", "yu-myeong-ha-da", "Nổi tiếng lừng danh"),
    ("훌륭하다", "hul-lyung-ha-da", "Xuất sắc tuyệt vời"), ("대단하다", "dae-dan-ha-da", "To lớn cừ khôi"),
    ("특별하다", "teuk-byeol-ha-da", "Đặc biệt độc đáo"), ("평범하다", "pyeong-beom-ha-da", "Bình thường giản dị"),
    ("귀하다", "gwi-ha-da", "Quý giá trân quý"), ("흔하다", "heun-ha-da", "Phổ biến nhan nhản")
]
for h, r, v in adj_raw:
    add(h, r, v, "adjectives", "Tính từ", "Sơ cấp 1", f"날씨나 물건이 참 {h}.", f"Thời tiết hay đồ vật này thật {v}.")

print(f"Total authentic items generated: {len(items)}")

target_path = os.path.join(os.path.dirname(__file__), "..", "src", "data", "massiveVocab.json")
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(items, f, ensure_ascii=False, indent=2)

print(f"Successfully saved {len(items)} vocabulary words to {target_path}")
